---
- hosts: all
  become: yes
  tasks:
  - name: install httpd server
    yum: name={{item}} state=installed
    with_items:
      - httpd
      - mod_ssl

  - name: ensure httpd started
    service: name=httpd state=started enabled=yes

  - name: copy apache content
    copy:
      remote_src: true
      src: /var/test/www
      dest: /var/www/html
      mode: 0755
    notify: restart httpd
  handlers:
  - name: restart httpd
    service:
      name: httpd
      state: restarted
