- hosts: all
  remote_user: admin
  become: yes
  become_method: sudo
  tasks:
  - name: login to docker registry
    docker_login:
      username: "{{ docker_hub_username }}"
      password: "{{ docker_hub_password }}"
      email: "{{ docker_hub_email }}"
  - name: create custom docker container
    docker_container:
      name: "{{cont_name}}"
      image: kumardokcer/ansibledocker:v1
      state: "{{state}}"
      exposed_ports:
        - 80
      ports:
        "80:80"
