- hosts: all
  become: true
  tasks:
  - name: Add pool member
    bigip_pool_member:
        server: "35.193.117.86"
        user: "admin"
        password: ""
        state: "present"
        pool: "webserver_pool"
        partition: "Common"
        host: "192.168.1.1"
        port: 80
        description: "web server"
        connection_limit: 100
        rate_limit: 50
        ratio: 2
    delegate_to: localhost
