- hosts: 127.0.0.1
  tasks:
  - name: Add virtual server
    bigip_virtual_server:
        server: 35.193.117.86
        user: admin
        password: ansible
        state: present
        partition: MyPartition
        name: myvirtualserver
        destination: "104.196.219.127"
        port: 443
        pool: "mypool"
        snat: Automap
        description: Test Virtual Server
        all_profiles:
            - http
            - clientssl
        enabled_vlans:
            - /Common/vlan2
        delegate_to: localhost
   
