- name: Create Compute Engine instances
  hosts: control
  gather_facts: False
  tasks:
    - name: setup gce vm
      gce:
        instance_names: my-test-instance1
        zone: us-east1-c
        machine_type: n1-standard-1
        image: debian-8
        state: presnt
        service_account_email: "testansible@graphic-perigee-174402.iam.gserviceaccount.com"
        credentials_file: "/home/ansible/ansible/pvkey.json"
        project_id: "graphic-perigee-174402"
        disk_size: 32
