- hosts: all
  become: true
  vars: 
    download_dir: /opt
    jdk_name: "{{ls -l /opt/jdk*}}"
    java_name: "{{download_dir}}/{{jdk_name}}"
  tasks:
  - name: Download and extract jdk
    unarchive:
      src: http://35.193.24.16/jdk-9.0.1_linux-x64_bin.tar.gz
      dest: /opt
      remote_src: yes

  - name: Fix ownership
    file: state=directory path={{java_name}} owner=root group=root recurse=yes

  - name: Make Java available for system
    alternatives:
      name: java
      path: "{{java_name}}/bin/java"
