- name: setup ad
  hosts: all
  tasks:
  - name: Install AD-Domain-Services feature
    win_feature:
      name=AD-Domain-Services
      include_management_tools=yes
      include_sub_features=yes
      state=present
 
