- name: install web server
  hosts: all
  tasks:
  - name: install web server
    win_feature:
      name: Web-Server
      state: present
      restart: True
      include_sub_features: True
      include_management_tools: True
 
