- name: install AD server
  hosts: all
  tasks:
  - name: install AD server
    win_feature:
      name: AD-Domain-Services
      state: present
      restart: True
      include_management_tools: True
    
  - name: promote to remote controller
    win_domain_controller:
      dns_domain_name: kumar.com
      domain_admin_user: kquicklogin@kumar.com
      domain_admin_password: Password@123
      safe_mode_password: Password@123
      state: domain_controller
      log_path: c:\ansible_win_domain_controller.txt
      
  - name: Reboot server
    win_shell: Restart-Computer -Force
      
