- name: install AD server
  hosts: all
  tasks:
  - name: install AD server
    win_feature:
      name: AD-Domain-Services
      state: present
      restart: yes
      include_sub_features: yes
      include_management_tools: yes
      
  - name: Reboot server
    win_shell: Restart-Computer -Force
      
