---
- hosts: all
  tasks:
  - name: setup acl for windows user
    win_acl:
      path: "{{path}}"
      user: ranga.com\sandeep
      rights: Read,Write,Modify
      type: allow
      state: present
