---
- hosts: all
  tasks:
  - name: setup acl for windows user
    win_acl:
      path: "C:\testdir\testfile"
      user: sandeep
      rights: FullControl
      type: allow
      state: present
      inherit: ContainerInherit, ObjectInherit
      propagation: 'None'
